services:

  worker1:
    build: ./worker
    environment:
      - WORKER_NAME=Worker1

  worker2:
    build: ./worker
    environment:
      - WORKER_NAME=Worker2

  worker3:
    build: ./worker
    environment:
      - WORKER_NAME=Worker3

  load-balancer:
    build: ./load-balancer
    ports:
      - "9090:7000"

  locust:
    image: locustio/locust
    volumes:
      - ./locust:/mnt/locust
    command: >
      -f /mnt/locust/locustfile.py
      --host=http://load-balancer:7000
    ports:
      - "8089:8089"
