# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprocessor.proto\"\x1d\n\x07RawData\x12\x12\n\ninput_text\x18\x01 \x01(\t\"=\n\rProcessedData\x12\x13\n\x0boutput_text\x18\x02 \x01(\t\x12\x17\n\x0f\x63haracter_count\x18\x03 \x01(\x05\x32<\n\rDataProcessor\x12+\n\rTransformText\x12\x08.RawData\x1a\x0e.ProcessedData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWDATA']._serialized_start=19
  _globals['_RAWDATA']._serialized_end=48
  _globals['_PROCESSEDDATA']._serialized_start=50
  _globals['_PROCESSEDDATA']._serialized_end=111
  _globals['_DATAPROCESSOR']._serialized_start=113
  _globals['_DATAPROCESSOR']._serialized_end=173
# @@protoc_insertion_point(module_scope)
